FP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('fp_app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

fp_app/urls.py
from django.urls import path

from .views import index_view, project_views, client_views, \
    boundary_views, data_function_views, transactional_function_views, \
    counting_views, operation_views


app_name = 'fp_app'
urlpatterns = [
    path('', index_view.index, name='index'),

    path('project/', project_views.IndexView.as_view(), name='project_index'),
    path('project/<int:pk>/', project_views.DetailView.as_view(), name='project_detail'),
    path('project/new', project_views.CreateView.as_view(), name='project_new'),
    path('project/delete/<int:pk>', project_views.DeleteView.as_view(), name='project_delete'),
    path('project/update/<int:pk>', project_views.UpdateView.as_view(), name='project_update'),
    
    path('client/', client_views.IndexView.as_view(), name='client_index'),
    path('client/<int:pk>/', client_views.DetailView.as_view(), name='client_detail'),
    path('client/new', client_views.CreateView.as_view(), name='client_new'),
    path('client/delete/<int:pk>', client_views.DeleteView.as_view(), name='client_delete'),
    path('client/update/<int:pk>', client_views.UpdateView.as_view(), name='client_update'),
    
    path('boundary/', boundary_views.IndexView.as_view(), name='boundary_index'),
    path('boundary/<int:pk>/', boundary_views.DetailView.as_view(), name='boundary_detail'),
    path('boundary/new', boundary_views.CreateView.as_view(), name='boundary_new'),
    path('boundary/delete/<int:pk>', boundary_views.DeleteView.as_view(), name='boundary_delete'),
    path('boundary/update/<int:pk>', boundary_views.UpdateView.as_view(), name='boundary_update'),
    
    path('data-function/', data_function_views.IndexView.as_view(), name='data_function_index'),
    path('data-function/<int:pk>/', data_function_views.DetailView.as_view(), name='data_function_detail'),
    path('data-function/new', data_function_views.CreateView.as_view(), name='data_function_new'),
    path('data-function/delete/<int:pk>', data_function_views.DeleteView.as_view(), name='data_function_delete'),
    path('data-function/update/<int:pk>', data_function_views.UpdateView.as_view(), name='data_function_update'),
    
    path('transactional-function/', transactional_function_views.IndexView.as_view(),
         name='transactional_function_index'),
    path('transactional-function/<int:pk>/', transactional_function_views.DetailView.as_view(),
         name='transactional_function_detail'),
    path('transactional-function/new', transactional_function_views.CreateView.as_view(),
         name='transactional_function_new'),
    path('transactional-function/delete/<int:pk>', transactional_function_views.DeleteView.as_view(),
         name='transactional_function_delete'),
    path('transactional-function/update/<int:pk>', transactional_function_views.UpdateView.as_view(),
         name='transactional_function_update'),
    
    path('counting/', counting_views.IndexView.as_view(), name='counting_index'),
    path('counting/<int:pk>/', counting_views.DetailView.as_view(), name='counting_detail'),
    path('counting/new', counting_views.CreateView.as_view(), name='counting_new'),
    path('counting/delete/<int:pk>', counting_views.DeleteView.as_view(), name='counting_delete'),
    path('counting/update/<int:pk>', counting_views.UpdateView.as_view(), name='counting_update'),

    path('operation/', operation_views.IndexView.as_view(), name='operation_index'),
    path('operation/<int:pk>/', operation_views.DetailView.as_view(), name='operation_detail'),
    path('operation/new', operation_views.CreateView.as_view(), name='operation_new'),
    path('operation/delete/<int:pk>', operation_views.DeleteView.as_view(), name='operation_delete'),
    path('operation/update/<int:pk>', operation_views.UpdateView.as_view(), name='operation_update'),
    
]

templates/base.html
<html>
<head>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'fp_app/img/logo.ico' %}"/>
    <link rel="stylesheet" href="{% static  'fp_app/css/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/2ce17f4bde.js" crossorigin="anonymous"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    {% block head %}{% endblock %}
    <title>
        {% block title %} Function Points {% endblock %}
    </title>
</head>
<body>
    <div class="container-fluid">
        {% block navbar %}
            {% include 'nav.html' %}
        {% endblock %}

        {%  block content %}
        {%  endblock %}
    </div>
    <script src="{% static 'fp_app/js/jquery-3.4.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="{% static 'fp_app/js/gijgo/core.js' %}"></script>
    <script src="{% static 'fp_app/js/gijgo/datepicker.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"
            integrity="sha256-AdQN98MVZs44Eq2yTwtoKufhnU+uZ7v2kXnD5vqzZVo=" crossorigin="anonymous"></script>
    <script src="{%  static 'fp_app/js/spin.js' %}"></script>
    <script src="{%  static 'fp_app/js/jquery.spin.js'%}"></script>
    <script src="{%  static 'fp_app/js/jquery.blockUI.js'%}"></script>

    <div id="spinner-div"></div>

     {%  block js-hack %}
     {% endblock %}

    <script>
        function loadingSpinner(){
            $('#spinner-div').spin(
                       {
                           'lines': 13,
                           'length': 28,
                           'width': 14,
                           'radius': 42,
                           'scale': 1.75,
                           'corners': 0.1,
                           'opacity': 0.25,
                           'rotate': 0,
                           'direction': 1,
                           'speed': 1.0,
                           'trail': 60,
                           'color': '#ffffff',
                       }
                   );

             $.blockUI({'message': null});
        }

        $(document).ready(
            function() {

               $('[data-toggle="tooltip"]').tooltip();

               $('form').submit(loadingSpinner);
               $('a.page-link, a[href*="/"]').click(loadingSpinner);
            });
    </script>
</body>
</html>

templates/confirm_delete_generic.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>

    <div class="row align-content-md-center">
        <div class="col"></div>
        <div class="card col-md-6">
            <div class="card-body">
                <h5 class="card-title">Alert!</h5>
                <form method="post">
                    {% csrf_token %}
                    <p class="card-text">Are you sure you want to delete "{{ object }}"?</p>
                <input class='btn btn-danger' type="submit" value="Confirm">
                </form>
            </div>
        </div>
        <div class="col"></div>
    </div>

{% endblock %}

templates/detail_generic.html
{% extends 'base.html' %}

{% load model_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>

    <dl class="row">
    {% for name, value in fields_name_and_value %}

       {% if value and name != 'ID' and name not in exclude_fields|default:"|" %}
            <dt class="p-2 my-1 col-sm-2 col-lg-1 font-weight-bold bg-dark text-white">{{name}}</dt>
            <dd class="p-2 col-sm-10 col-lg-11 my-auto">{{value}}</dd>
        {% endif %}

    {% endfor %}
    </dl>

    <a class="btn btn-primary btn-sm" href="{{ index_url }}">{%  model_name view %}&nbsp;List</a>
    <a class="btn btn-outline-primary btn-sm" href="{% url update_url_str  object.id %}">Edit</a>

{% endblock %}

templates/form_generic.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{{  form.media }}

{% block title %}{{ title }} {% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-sm btn-outline-success">Save</button>
        <button type="reset" class="btn btn-sm btn-outline-secondary">Clear</button>
    </form>
{% endblock %}

{% block js-hack %}
<script>
    $(document).ready(function(){
        //small controls in the filter form
        $('.form-control').addClass('form-control-sm');

        //moment().locale(['pt-br']);
        $('.datepicker').datepicker({
            //locale: 'pt-br',
            //format: 'dd/mm/YYYY',
            uiLibrary: 'bootstrap4',
            size: 'default',
            iconsLibrary: 'fontawesome',
            value: moment().format("L"),
            rightIcon: '<i class="fas fa-calendar-alt"></i>'
        });

        // disabling fields
        {% for field in form %}
            {% if field.name in disabled_fields|default:0 %}
                $('#{{ field.id_for_label }}').prop('disabled', 'disabled');
            {% endif %}
            {% if field.name in readonly_fields|default:0 %}
                $('#{{ field.id_for_label }}').prop('readonly', 'true');
            {% endif %}
        {% endfor %}

    });
</script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}<meta name="viewport" content="width=device-width, initial-scale=1">{% endblock %}

{% block navbar %}
<style>
    body > div {
        background: url({{ request.scheme }}://{{ request.META.HTTP_HOST }}{% static 'fp_app/img/background-image2.jpg' %}) no-repeat center center fixed;
        background-size: cover;
        min-height: 100vh;
        width: 100vw;
    }
 </style>
{% endblock %}

{%  block content %}
    <div class="row h-100">

        <div class="col mt-md-5">
                <table>
                    <tr>
                        <td style="width: 25%; max-width: 48px">
                            <img src="{% static 'fp_app/img/logo.png' %}" class='w-100'>
                        </td>
                        <td>
                             <h3 class="text-white">Function Point Analysis</h3>
                            <span class="my-0"><a class="text-white" href="http://mangeli.com.br">http://mangeli.com.br</a></span>
                        </td>
                    </tr>
                </table>
        </div>
        <div class="col-md-6 col-lg-4 my-auto h-auto">
            <div class="card my-md-5 bg-primary text-white">
                <div class="card-header">
                    <h3 class="text-white">Login</h3>
                </div>
                <div class="card-body">
                <form>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Usuário</label>
                        <input type="email" class="form-control form-control-sm" id="user" aria-describedby="userHelp" placeholder="nome de usuário">
                        {%  comment %}<small id="emailHelp" class="form-text text-muted">Nunca vamos compartilhar seu email, com ninguém.</small>{%  endcomment %}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword">Senha</label>
                        <input type="password" class="form-control form-control-sm" id="exampleInputPassword1" placeholder="Senha">
                    </div>

                        {% comment %}
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Clique em mim</label>
                    </div>
                        {% endcomment %}
                     <div class="text-right">
                        <button type="submit" class="btn btn-outline-secondary btn-sm">Enviar</button>
                     </div>
                </form>
                </div>
            </div>
        </div>
    </div>
<a style="position:fixed;bottom:0;right:0;background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px" href="https://unsplash.com/@lorenzoherrera?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge" target="_blank" rel="noopener noreferrer" title="Download free do whatever you want high-resolution photos from Lorenzo Herrera">Image: Lorenzo Herrera</span><span style="display:inline-block;padding:2px 3px"><svg xmlns="http://www.w3.org/2000/svg" style="height:12px;width:auto;position:relative;vertical-align:middle;top:-2px;fill:white" viewBox="0 0 32 32"><title>unsplash-logo</title><path d="M10 9V0h12v9H10zm12 5h10v18H0V14h10v9h12v-9z"></path></svg></span><span style="display:inline-block;padding:2px 3px"></a>
{%  endblock %}

 {%  block js-hack %}

 {% endblock %}

templates/index_generic.html
{%  extends 'base.html' %}

{% load render_table from django_tables2 %}

{% load crispy_forms_tags %}

{% block title %} {{ title }} {% endblock %}


{% block content %}
    <h1>{{ title }}</h1>
            <form method="get">
                {% csrf_token %}
                <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#filter" role="button">Filter</a>
                <a class="btn btn-outline-primary btn-sm" href="{{ create_url }}">New</a>
                {% if has_filter %}
                    <div class="collapse.show" id="filter">
                {% else %}
                    <div class="collapse" id="filter">
                {% endif %}


                {% for field in filter.form %}
                    {% if forloop.counter0 == 0 %}
                        <div class="row">
                    {% elif forloop.counter0|divisibleby:2 and forloop.counter < filter.form.fields|length %}
                        </div>
                        <div class="row">
                    {% endif %}
                    {% if forloop.counter == filter.form.fields|length %}
                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col-sm-6">{{ field | as_crispy_field }}</div>
                        {% else %}
                            <div class="col-sm-12">{{ field | as_crispy_field }}</div>
                        {% endif %}
                        </div>
                    {% else %}
                        <div class="col-sm-6">{{ field | as_crispy_field }}</div>
                    {%  endif  %}
                {% endfor %}

{#                    {{ filter.form | crispy }}#}
                    <button type="submit" class="btn btn-outline-success btn-sm">Search</button>
                    <input type="reset" class="btn btn-outline-secondary btn-sm" value="Clear fields">
                    {% if has_filter %}
                        <a href="{{ self_url }}" class="btn btn-outline-warning btn-sm">Reset Filter</a>
                    {% endif %}
                </div>

            </form>
    {%  render_table table %}
{%  endblock %}

{% block js-hack %}
<script>
    $(document).ready(function(){
        //small controls in the filter form
        $('.form-control').addClass('form-control-sm');
        $('.dateinput').datepicker({
            //locale: 'pt-br',
            //format: 'dd/mm/YYYY',
            uiLibrary: 'bootstrap4',
            size: 'default',
            iconsLibrary: 'fontawesome',
            value: moment().format("L"),
            rightIcon: '<i class="fas fa-calendar-alt"></i>'
        });
    });
</script>
{% endblock %}

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark py-0 mb-sm-3">
    <a class="navbar-brand" href="{% url 'fp_app:index' %}">
        <img src="{% static 'fp_app/img/logo.png' %}" width="30">
{#        FP#}
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Working Area
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'fp_app:counting_index' %}">Manage Counts Ref.</a>
                    <a class="dropdown-item" href="#">Populate Count</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Admin Area
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'fp_app:client_index' %}">Client</a>
                    <a class="dropdown-item" href="{% url 'fp_app:project_index' %}">Project</a>
                    <a class="dropdown-item" href="{% url 'fp_app:boundary_index' %}">Boundary</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'fp_app:data_function_index' %}">Data Function</a>
                    <a class="dropdown-item" href="{% url 'fp_app:transactional_function_index' %}">Transactional Function</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'fp_app:counting_index' %}">Counting Ref.</a>
                    <a class="dropdown-item" href="{% url 'fp_app:operation_index' %}">Operation</a>
                </div>
            </li>


        </ul>
    </div>
</nav>

templates/table.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
<div class="table-container">
    {% block table %}
        <table {% render_attrs table.attrs class="table" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead {{ table.attrs.thead.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <th {{ column.attrs.th.as_html }}>
                        {% if column.orderable %}
                            <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                        {% else %}
                            {{ column.header }}
                        {% endif %}
                    </th>
                {% endfor %}
                </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            {% if table.has_footer %}
            <tfoot {{ table.attrs.tfoot.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
                </tr>
            </tfoot>
            {% endif %}
            {% endblock table.tfoot %}
        </table>
    {% endblock table %}

    {% block pagination %}
        {% if table.page and table.paginator.num_pages > 1 %}
        <nav aria-label="Table navigation">
            <ul class="pagination justify-content-center">
            {% if table.page.has_previous %}
                {% block pagination.previous %}
                <li class="previous page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                        {% trans 'previous' %}
                    </a>
                </li>
                {% endblock pagination.previous %}
            {% endif %}
            {% if table.page.has_previous or table.page.has_next %}
            {% block pagination.range %}
            {% for p in table.page|table_page_range:table.paginator %}
                <li class="page-item{% if table.page.number == p %} active{% endif %}">
                    <a class="page-link" {% if p != '...' %}href="{% querystring table.prefixed_page_field=p %}"{% endif %}>
                        {{ p }}
                    </a>
                </li>
            {% endfor %}
            {% endblock pagination.range %}
            {% endif %}
            {% if table.page.has_next %}
                {% block pagination.next %}
                <li class="next page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="page-link">
                        {% trans 'next' %}
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endblock pagination.next %}
            {% endif %}
            </ul>
        </nav>
        {% endif %}
    {% endblock pagination %}
</div>
{% endblock table-wrapper %}